name: 'Deploy Library'
description: 'Deploy library by building it and uploading it to a bucket'
inputs:
  PUBLISH_PACKAGE:
    description: 'Should the package be published to the NPM registry?'
    default: false
  GCLOUD_BUCKET_NAME:
    description: 'Bucket name to upload library to'
    required: true
  GCLOUD_ZONE:
    description: 'Default region or zone'
    default: europe-west2-a

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    PUBLISH_PACKAGE: ${{ inputs.PUBLISH_PACKAGE }}
    GCLOUD_BUCKET_NAME: ${{ inputs.GCLOUD_BUCKET_NAME }}
    GCLOUD_ZONE: ${{ inputs.GCLOUD_ZONE }}