name: 'Thank You Action'

inputs:
  WEBHOOK_URL:
    description: 'Slack Webhook URL'
    required: true
  DEPLOYMENT_TARGET:
    description: 'The deployment target (Production / Staging)'
    required: true

runs:
  using: "composite"
  steps:
    - name: Check out Git repository
      uses: actions/checkout@v3

    - name: Record Deployment Result
      id: deployment_message
      shell: bash
      if: always()
      run: |
        if [ "${{ job.status }}" = "success" ]; then
          MESSAGE=":white_check_mark: Deployment successful"
        else
          MESSAGE=":x: Deployment failed"
        fi
        echo "MESSAGE=${MESSAGE}" >> $GITHUB_OUTPUT

    - uses: slackapi/slack-github-action@v1.24.0
      name: Send custom JSON data to Slack workflow
      id: slack
      with:
        payload: |
          {
            "text": "this is a test"
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.WEBHOOK_URL_SLACK }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK