name: 'Custom Action'
description: 'A custom action that prints a message'
inputs:
  message:
    description: 'The message to print'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '12'

    - name: Install Node.js dependencies
      run: npm install