name: 'Thank You Action'

inputs:
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true
  WEBHOOK_URL:
    description: 'Slack Webhook URL'
    required: true
  DEPLOYMENT_TARGET:
    description: 'The deployment target (Production / Staging)'
    required: true
  DEPLOYMENT_SUCCESSFUL:
    description: 'If the deployment was sucessful'
    required: true

runs:
  using: "composite"
  steps:
    - name: Check out Git repository
      uses: actions/checkout@v3

    - name: Record Deployment Result
      id: deployment_message
      shell: bash
      if: always()
      run: |
        if [ "${{ job.status }}" = "success" ]; then
          MESSAGE=":white_check_mark: Deployment successful"
        else
          MESSAGE=":x: Deployment failed"
        fi
        echo "MESSAGE=${MESSAGE}" >> $GITHUB_OUTPUT

    - name: Send custom JSON data to Slack workflow
      id: slack
      uses: slackapi/slack-github-action@v1.24.0
      with:
        payload: |
          {
            "username": "Tech Logger",
            "icon_url": "https://a.slack-edge.com/80588/img/apps/default_new_app_icon.png",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "${{ steps.deployment_message.outputs.MESSAGE }}"
                }
              },
              {
                "type": "divider"
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Repository* \n <https://github.com/${{ github.repository }}|${{ github.repository }}>"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Triggered By* \n ${{ github.triggering_actor }}"
                  }
                ]
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Commit* \n <https://github.com/${{ github.repository }}/commit/${{ github.workflow_sha }}|${{ github.workflow_sha }}>"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Target* \n ${{ inputs.DEPLOYMENT_TARGET }}"
                  }
                ]
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": " "
                  }
                ]
              },
              {
                "type": "divider"
              },
              {
                "type": "context",
                "elements": [
                  {
                    "type": "mrkdwn",
                    "text": "<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|More Details>"
                  }
                ]
              },
              {
                "type": "divider"
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK