name: 'Run Tests'
     // Example of a custom action
    // action.yml
    name: 'Custom Action'
    description: 'A custom action that prints a message'
    inputs: message:
    description: 'The message to print'
    required: true
    runs:
    	using: 'node12'
    	main: 'index.js'
    

     
