name: 'Thank You Action'

inputs:
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true
  WEBHOOK_URL:
    description: 'Slack Webhook URL'
    required: true
  DEPLOYMENT_TARGET:
    description: 'The deployment target (Production / Staging)'
    required: true
  DEPLOYMENT_SUCCESSFUL:
    description: 'If the deployment was sucessful'
    required: true

runs:
  using: "composite"
  steps:
    - name: Check out Git repository
      uses: actions/checkout@v3

    - name: Send custom JSON data to Slack workflow
      id: slack
      uses: slackapi/slack-github-action@v1.24.0
      with:
        # This data can be any valid JSON from a previous step in the GitHub Action
        payload: |
          {
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "${DEPLOYMENT_MESSAGE}"
                }
              },
              {
                "type": "divider"
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Repository* \n <${{ github.repositoryUrl }}|${{ github.repository }}>"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Triggered By* \n ${{ github.triggering_actor }}"
                  }
                ]
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Commit* \n <${GITHUB_COMMIT_URL}|${GITHUB_SHA}>"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Target* \n ${{ inputs.DEPLOYMENT_TARGET }}"
                  }
                ]
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": " "
                  }
                ]
              },
              {
                "type": "divider"
              },
              {
                "type": "context",
                "elements": [
                  {
                    "type": "mrkdwn",
                    "text": ":louis-1::louis-2::louis-3: <${GITHUB_WORKFLOW_URL}|More Details>"
                  }
                ]
              },
              {
                "type": "divider"
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK