name: 'Thank You Action'

inputs:
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true
  WEBHOOK_URL:
    description: 'Slack Webhook URL'
    required: true
  DEPLOYMENT_TARGET:
    description: 'The deployment target (Production / Staging)'
    required: true
  DEPLOYMENT_SUCCESSFUL:
    description: 'If the deployment was sucessful'
    required: true

runs:
  using: 'node12'
  main: 'dist/index.js'
