name: 'Thank You Action'

inputs:
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true
  WEBHOOK_URL:
    description: 'Slack Webhook URL'
    required: true
  DEPLOYMENT_TARGET:
    description: 'The deployment target (Production / Staging)'
    required: true
  DEPLOYMENT_SUCCESSFUL:
    description: 'If the deployment was sucessful'
    required: true

runs:
  using: "composite"
  steps:
    - name: Check out Git repository
      uses: actions/checkout@v3

    - name: Check Deployment Status
      run: |
        if [ "${{ github.event.workflow_run.conclusion }}" == "success" ]; then
          echo "Deployment succeeded!"
          echo "::set-env name=DEPLOYMENT_STATUS::Succeeded"
          echo "::set-env name=DEPLOYMENT_MESSAGE:::white_check_mark: *Deployment Succeeded*"
        else
          echo "Deployment failed!"
          echo "::set-env name=DEPLOYMENT_STATUS::Failed"
          echo "::set-env name=DEPLOYMENT_MESSAGE:::x: *Deployment Failed*"
        fi
        
        echo "DEPLOYMENT_STATUS=${DEPLOYMENT_STATUS}"
        echo "DEPLOYMENT_MESSAGE=${DEPLOYMENT_MESSAGE}"


    - name: Send custom JSON data to Slack workflow
      id: slack
      uses: slackapi/slack-github-action@v1.24.0
      with:
        # This data can be any valid JSON from a previous step in the GitHub Action
        payload: |
          {
            "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                }
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.WEBHOOK_URL }}