name: 'Deploy Package'
description: 'Deploy package by building it and publishing it to NPM'
inputs:
  PUBLISH_PACKAGE:
    description: 'Should the package be published to the NPM registry?'
    default: false

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    PUBLISH_PACKAGE: ${{ inputs.PUBLISH_PACKAGE }}