cron:
- description: "Submit geo links to be checked"
  url: /api/v1/private/link-status/check
  schedule: every 1 hours from 00:50 to 23:50
- description: "Update Slack on broken links"
  url: /api/v1/private/link-status/notify
  schedule: every 1 hours