cron:
- description: "Send Geo Links to be checked via the check-link-status cloud function"
  url: /api/v1/private/link-status/check
  schedule: every 1 hour
  target: offers
- description: "Get latest crypto coin prices"
  url: /api/v2/coins/latest/cache
  schedule: every 15 minutes
  target: prices