cron:
- description: "Send Geo Links to be checked via the check-link-status cloud function"
  url: /api/v1/private/link-status/check
  schedule: every 1 hours
  target: offers
- description: "Get latest crypto coin prices"
  url: /api/v2/coins/cache/latest
  schedule: every 15 minutes
  target: prices-
- description: "Get latest forex prices"
  url: /api/v2/forex/cache/latest
  schedule: every 15 minutes
  target: prices