name: 'Custom Action'
on: push
description: 'A custom action that prints a message'
inputs:
    message:
        description: 'The message to print'
required: true
runs:
  using: 'node12'
  main: 'index.js'
