name: Greeting from Mona

on: push

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          # For posting a rich message using Block Kit
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "${DEPLOYMENT_MESSAGE}"
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Repository* \n <${GITHUB_REPO_URL}|${GITHUB_REPOSITORY}>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Triggered By* \n ${GITHUB_ACTOR}"
                    }
                  ]
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Commit* \n <${GITHUB_COMMIT_URL}|${GITHUB_SHA}>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Target* \n ${DEPLOYMENT_TARGET}"
                    }
                  ]
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": " "
                    }
                  ]
                },
                {
                  "type": "divider"
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "mrkdwn",
                      "text": ":louis-1::louis-2::louis-3: <${GITHUB_WORKFLOW_URL}|More Details>"
                    }
                  ]
                },
                {
                  "type": "divider"
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.WEBHOOK_URL_SLACK }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK


