name: 'Run Tests'
inputs:
  DEPLOYMENT_TARGET:
    description: 'What environment are you trying to deploy to?'
    required: true
  DEPLOYMENT_SUCCESSFUL:
    description: 'Was the deployment successful?'
    default: false
  WEBHOOK_URL:
    description: 'The Slack webhook URL that the message will be sent to'
    required: true
